services:
  postgres:
    container_name: wisenotes_database
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: wisenotes_db
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - wisenotesdata:/var/lib/postgresql/data

  redis:
    image: redis:8.4.0-alpine
    container_name: wisenotes-redis
    ports:
      - "6379:6379"
    volumes:
      - wisenotes_redis:/data

volumes:
  wisenotesdata:
  wisenotes_redis:
